version: '3.8'
services:

  reverseproxy:
    container_name: hsa-lab7-reverseproxy
    build:
      context: ./nginx
      dockerfile: nginx.dockerfile
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /www/nginx-cache:/www/cache
    restart: always
    
  hsa-lab7:
    build:
      context: ../.
      dockerfile: ./src/hsa-lab7/Dockerfile
    depends_on:
      - reverseproxy
    container_name: hsa-lab7
    ports:
      - 5000:80